# @package _group_
architecture: LSTMCNNBaseline
multiscale: true
location_embeddings: true
text_encoder:
  name: LSTMEncoder
  hidden_size: 256
  bidirectional: false
  embedding_dim: 300
  glove: true
  dropout: 0.2
image_encoder:
  name: resnet18
  num_layers: 4
  pretrained: true
  freeze: true
mask_predictor:
  num_channels: 64
  kernel_size: 5
  stride: 2
  padding: 2