# @package _group_
architecture: ColorizationModel
multiscale: false
use_location_embeddings: false
full_resolution: true
text_encoder:
  name: LSTMEncoder
  hidden_size: 256
  bidirectional: true
  embedding_dim: 300
  glove: true
  w2v: true
  dropout: 0.2
  batch_first: true
image_encoder:
  name: resnet101
  num_layers: 2
  pretrained: true
  freeze: true
multimodal_encoder:
  topdown: true
  bottomup: true
  num_layers: 4
  num_kernels: 512
  connected: true
  kernel_size: 5
  stride: 2
  dilation: 1
  text_kernel_size: 1  
  layer: "conv"  # or film
mask_predictor:
  num_channels: 512
  kernel_size: 5
  stride: 2
  padding: 2
  num_classes: null
