name: bvpr
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - ipython=7.19.0
  - pip=20.3.3
  - cython=0.29.21
  - pip:
      - -r requirements.txt -f https://download.pytorch.org/whl/torch_stable.html
      - ipdb
      - hydra-core
      - -e .
