name: bvpr
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - ipython=7.19.0
  - pip=20.3.3
  - conda-forge::hydra-core=1.0.4
  - pip:
      - -r requirements.txt -f https://download.pytorch.org/whl/torch_stable.html
      - ipdb
      - -hydra-core
      - -e .