seed: 1
image_size: 640
threshold: null
checkpoint: null
output: null

defaults:
  - dataset: UNC
  - optimizer: Adam
  - trainer: train
  - hydra/job_logging: disabled

criterion: "MaskedMultiScaleBCELoss"

# data loader
loader:
  batch_size: 32
  pin_memory: false
  num_workers: 16

# hydra-specific
hydra:
  run:
    dir: .