seed: 1

defaults:
  - model: Baseline
  - dataset: UNC
  - optimizer: Adam
  - scheduler: ReduceLROnPlateau
  - trainer: train
  - hydra/job_logging: disabled

hydra:
  run:
    dir: .

# data loader
loader:
  batch_size: 16
  pin_memory: false
  num_workers: 16

# logger (tensorboard)
logger:
  name: null
  version: null
  save_dir: ~/logs/intphys/debug

# checkpoint
checkpoint:
  save_top_k: 1
  save_last: true
  verbose: true
  monitor: "val_accuracy"
  mode: "max"
  prefix: ""
  filepath: null

# resume training
checkpoint_path: null